3.0.0-BETA

diff --git a/lib/libdevuansdk/zlibs/bootstrap b/lib/libdevuansdk/zlibs/bootstrap
--- a/lib/libdevuansdk/zlibs/bootstrap
+++ b/lib/libdevuansdk/zlibs/bootstrap
@@ -17,17 +17,18 @@
 # You should have received a copy of the GNU General Public License
 # along with this source code. If not, see <http://www.gnu.org/licenses/>.
 
-vars+=(bootstrap_tgz_stage3 bootstrap_tgz_stage4 TAR_STAGE4)
 arrs+=(base_packages_option core_packages_option extra_packages_option)
 arrs+=(purge_packages_option)
 arrs+=(core_packages base_packages extra_packages purge_packages)
 
 bootstrap_complete_base() {
 	fn bootstrap_complete_base "$@"
-	req=(arch)
+	req=(workdir strapdir os arch release)
 	ckreq || return 1
 
 	notice "bootstrapping $os $arch base"
+	
+	mkdir -p $strapdir	
 
 	export LANG=C
 	export LC_ALL=C
@@ -56,6 +57,7 @@ bootstrap_complete_base() {
 
 	sudo DEBOOTSTRAP_DIR="$LIBPATH/extra/debootstrap" "$LIBPATH/extra/debootstrap/debootstrap" \
 		--keyring="$LIBPATH/extra/devuan-keyring/keyrings/devuan-archive-keyring.gpg" \
+		--include=wget,ca-certificates \
 		--foreign \
 		--arch $arch $release $strapdir $mirror || zerr
 
@@ -69,8 +71,6 @@ bootstrap_complete_base() {
 	sudo chroot $strapdir \
 		/debootstrap/debootstrap --second-stage || zerr
 
-	blend_bootstrap_setup || zerr
-
 	## write all system configuration
 	notice "writing system configuration"
 	conf_print_debconf     | sudo tee $strapdir/debconf.set              >/dev/null
@@ -81,61 +81,110 @@ bootstrap_complete_base() {
 	conf_print_resolvconf  | sudo tee $strapdir/etc/resolv.conf          >/dev/null
 	conf_print_sourceslist | sudo tee $strapdir/etc/apt/sources.list     >/dev/null
 	#conf_print_locales     | sudo tee $strapdir/etc/profile.d/locales.sh >/dev/null
+}
 
-	## write third-stage for chroot
-	bootstrap_config_thirdstage | sudo tee $strapdir/thirdstage >/dev/null
+bootstrap_setup_base() {
+	fn bootstrap_setup_base "$@"
+	local target="$1"
+	req=(workdir strapdir os arch release)
+	ckreq || return 1
+	
+	notice "Installing gnupg-keys and locales"
+	
+	find $R/extra/gnupg-keys -type f -name "*.asc" -exec cp {} $strapdir/home \;
+	
+	echo \
+"
+deb http://${url}${root} ${release} main
+deb-src http://${url}${root} ${release} main
 
-	## chroot into it and configure further
-	## debootstrap stage 3
-	notice "running debootstrap stage 3"
+deb http://${url}${root} ${release}-updates main
+deb-src http://${url}${root} ${release}-updates main
 
+deb http://${url}${root} ${release}-security main
+deb-src http://${url}${root} ${release}-security main" > $strapdir/etc/apt/sources.list
 
-	chroot-script -d thirdstage || zerr
-
-	[[ $APT_CACHE = 1 ]] && {
-		notice "adding apt cache gpg pubkey"
-		cat <<EOF | sudo tee ${strapdir}/addcachepubkey >/dev/null
-#!/bin/sh
-gpgkey="$(gpg --export -a $aptcachegpg)"
-printf "%s" "\$gpgkey" | apt-key add -
+	cat << EOF | sudo tee $target/setup_locales >/dev/null
+#!/bin/sh	
+## setup locales
+apt-key add /home/*.asc
+rm -f /home/*.asc
+apt-get update
+apt-get --yes --force-yes install locales
+sed -e 's/# en_US.UTF-8/en_US.UTF-8/' -i /etc/locale.gen
+locale-gen en_US.UTF-8
+update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
+apt-get clean
 EOF
-		chroot-script addcachepubkey || zerr
-	}
 
-	if [[ -n "$TAR_STAGE4" ]]; then
-		bootstrap_tar_pack   "$bootstrap_tgz_stage3"             || zerr
-		bootstrap_tar_unpack "$bootstrap_tgz_stage4" "$strapdir" || zerr
-	else
-		bootstrap_tar_pack   "$bootstrap_tgz_stage3"             || zerr
-		bootstrap_tar_unpack "$bootstrap_tgz_stage3" "$strapdir" || zerr
-	fi
+	chroot-script -d setup_locales $target || zerr
 }
 
 bootstrap_config_thirdstage() {
 	fn bootstrap_config_thirdstage
-	req=(core_packages base_packages)
+	req=(R os strapdir arch release core_packages base_packages extra_packages)
 	ckreq || return 1
 
-	cat << EOF
+	cat << EOF | sudo tee $strapdir/thirdstage >/dev/null
 #!/bin/sh
+## check if all our core,base and extra packages exist
+
 apt-get update
-debconf-set-selections /debconf.set
+allpkgs="\$(apt-cache search '.' | cut -d' ' -f1)"
 
-echo "${rootcredentials}" | chpasswd
-sed -i -e 's/KERNEL\!=\"eth\*|/KERNEL\!=\"/' \
-	/lib/udev/rules.d/75-persistent-net-generator.rules
-rm -f /etc/udev/rules.d/70-persistent-net.rules
-export DEBIAN_FRONTEND=noninteractive
+for i in ${core_packages} ; do
+	printf "%s" "\$allpkgs" | grep -q "^\$i$" || {
+		case "\$i" in
+			--*) continue ;;
+			*)   missing="\$missing \$i" ;;
+		esac
+	}
+done
 
-apt-get --yes --force-yes install ${core_packages_option} ${core_packages}
-apt-get --yes --force-yes install ${base_packages_option} ${base_packages}
-apt-get --yes --force-yes purge  ${purge_packages_option} ${purge_packages}
+[ -n "\$missing" ] && {
+	printf "\033[1;31m[!!] some core packages don't exist\033[0m\n"
+	printf "%s\n" "\$missing"
+	exit 1
+}
+
+for i in ${base_packages} ; do
+	printf "%s" "\$allpkgs" | grep -q "^\$i$" || {
+		case "\$i" in
+			--*) continue ;;
+			*)   missing="\$missing \$i" ;;
+		esac
+	}
+done
+
+[ -n "\$missing" ] && {
+	printf "\033[1;31m[!!] some base packages don't exist\033[0m\n"
+	printf "%s\n" "\$missing"
+	exit 1
+}
+
+for i in ${extra_packages} ; do
+	printf "%s" "\$allpkgs" | grep -q "^\$i$" || {
+		case "\$i" in
+			--*) continue ;;
+			*)   missing="\$missing \$i" ;;
+		esac
+	}
+done
+
+[ -n "\$missing" ] && {
+	printf "\033[1;31m[!!] some extra packages don't exist\033[0m\n"
+	printf "%s\n" "\$missing"
+	exit 1
+}
+
+dpkg --configure -a
+
+apt-get --yes --force-yes install ${core_packages}
+apt-get --yes --force-yes install ${base_packages}
+apt-get --yes --force-yes install ${extra_packages}
+[[ ${#purge_packages[*]} != 0 ]] && apt-get --yes --force-yes purge ${purge_packages}
 apt-get --yes --force-yes autoremove
-
 apt-get clean
-
-sed -e 's/# en_US.UTF-8/en_US.UTF-8/' -i /etc/locale.gen
-locale-gen
 
 rm -f /debconf.set
 rm -f /etc/ssh/ssh_host_*
@@ -144,10 +193,82 @@ rm -f /root/.bash_history
 EOF
 }
 
+bootstrap_thirdstage() {
+	fn bootstrap_thirdstage
+	req=(R os strapdir arch release)
+	
+	## write third-stage for chroot
+	bootstrap_config_thirdstage | sudo tee $strapdir/thirdstage >/dev/null
+
+	## chroot into it and configure further
+	## debootstrap stage 3
+	notice "running debootstrap stage 3"
+
+	chroot-script -d thirdstage || zerr
+
+	#if [[ -n "$TAR_STAGE4" ]]; then
+	#	bootstrap_tar_pack   "$bootstrap_tgz_stage3"             || zerr
+	#	bootstrap_tar_unpack "$bootstrap_tgz_stage4" "$strapdir" || zerr
+	#else
+	#	bootstrap_tar_pack   "$bootstrap_tgz_stage3"             || zerr
+	#	bootstrap_tar_unpack "$bootstrap_tgz_stage3" "$strapdir" || zerr
+	#fi
+}	
+
+bootstrap_backup() {
+	fn bootstrap_backup "$@"
+	local squashfs_backup="$1"
+	req=(R os strapdir arch release squashfs_backup)
+	
+	notice "Creating $squashfs_backup in $workdir/squashfs"
+	silly
+
+	case "$arch" in
+		amd64|i386)
+			_compfilt="-Xbcj x86"
+			;;
+		arm*)
+			_compfilt="-Xbcj arm"
+			;;
+		*)
+			_compfilt=""
+			;;
+	esac
+	
+	pushd $workdir
+	mkdir -p squashfs
+	silly
+	[[ -f squashfs/filesystem.squashfs ]] && rm -f squashfs/$squashfs_backup
+	sudo mksquashfs $strapdir squashfs/$squashfs_backup \
+		-comp xz ${=_compfilt} -noappend || zerr
+	popd
+	
+	ckreq || return 1
+}
+
+bootstrap_restore() {
+	fn bootstrap_restore "$@"
+	local squashfs_backup="$1"
+	target="$2"
+	req=(R os strapdir arch release squashfs_backups)
+	
+	notice "Restoring $squashfs_backup in $workdir/$target"
+	
+	pushd $workdir
+	mkdir -p mnt
+	mount -t squashfs -o loop squashfs/$squashfs_backup mnt/
+	rsync -v -rlt -a mnt/ $target/
+	umount mnt/
+	rm -rf mnt
+	popd	
+	
+	ckreq || return 1
+}
+
 bootstrap_tar_pack() {
-	fn bootstrap_tar_pack
+	fn bootstrap_tar_pack "$@"
+	local bootstrap_tgz="$1"
 	req=(bootstrap_tgz)
-	bootstrap_tgz="$1"
 	ckreq || return 1
 
 	local _dest="$(dirname $bootstrap_tgz)"
diff --git a/lib/libdevuansdk/zlibs/iso b/lib/libdevuansdk/zlibs/iso
--- a/lib/libdevuansdk/zlibs/iso
+++ b/lib/libdevuansdk/zlibs/iso
@@ -38,82 +38,92 @@ EOF
 	chroot-script -d isoprep    || zerr
 }
 
-iso_setup_isolinux() {
-	fn iso_setup_isolinux
-	req=(workdir strapdir release arch url_pkg)
+iso_setup_kernel() {
+	fn iso_setup_kernel
+	req=(workdir strapdir)
 	ckreq || return 1
-
-	notice "setting up isolinux"
 
 	mkdir -p $workdir/binary/{live,isolinux}
 	act "copying kernel and initrd"
 	cp $strapdir/boot/vmlinuz* $workdir/binary/live/vmlinuz
 	cp $strapdir/boot/initrd*  $workdir/binary/live/initrd.img
-	#cp $strapdir/boot/memtest86+.bin $workdir/binary/live/memtest	
-	
-	rm -rf $workdir/syslinux
-	mkdir -p $workdir/syslinux
-	pushd $workdir/syslinux
-	wget $url_pkg/dists/$release/main/binary-$arch/Packages.gz
-	rm -f Packages
-	gzip -d Packages.gz
-	
-	line=`grep "^Filename:" Packages | grep "syslinux_"`
-	
-	line=${line##*/}
-	line=${line%%-*}
-	
-	wget $url_pkg/dists/$release/main/source/Sources.gz
-	rm -f Sources
-	gzip -d Sources.gz
-	
-	if grep "syslinux_" Sources | grep ".orig.tar.gz"
-	then
-	    line=`grep "syslinux_" Sources | grep ".orig.tar.g z"`
-	elif  grep "syslinux_" Sources | grep ".orig.tar.xz"
-	then
-	    line=`grep "syslinux_" Sources | grep ".orig.tar.xz"`
-	fi
-		
-	wget http://deb.debian.org/debian/pool/main/s/syslinux/syslinux_${line##*_}	
-	if [ ${line##*.} = "xz" ]; then
-		tar -Jxvf "syslinux_${line##*_}"
-	elif [ ${line##*.} = "gz" ]; then
-		tar -xzvf "syslinux_${line##*_}"
-	fi
+	#cp $strapdir/boot/memtest86+.bin $workdir/binary/live/memtest
+}
 
-	notice "building syslinux"
-	pushd syslinux-*
-	make
-	popd && popd
+iso_syslinux() {
+	fn iso_syslinux
+	req=(workdir)
+	ckreq || return 1
 	
-	case $arch in
-		i386)   bits="32"      ;;
-		amd64)  bits="64"      ;;
-	esac
+	cat <<EOF | sudo tee $workdir/env/download_syslinux
+#!/bin/sh
+rm -rf /home/syslinux 
+mkdir -p /home/syslinux
+cd /home/syslinux
+apt-get update
+apt-get source syslinux
+EOF
+
+	chroot-script -d download_syslinux $workdir/env || zerr
+
+	local version=$(find $workdir/env/home/syslinux -name "version")
+	sources=${version%/*}
+	sources=${sources##*/}
 	
-	case $bits in
-		"32")  efiboot="bootia32.efi"     ;;
-		"64")  efiboot="bootix32.efi"     ;;
-	esac
-		
-	cp -rav $workdir/syslinux/syslinux-*/bios/core/isolinux.bin                  $workdir/binary/isolinux/
-	cp -rav $workdir/syslinux/syslinux-*/bios/com32/chain/chain.c32              $workdir/binary/isolinux/
-	cp -rav $workdir/syslinux/syslinux-*/bios/com32/elflink/ldlinux/ldlinux.c32  $workdir/binary/isolinux/
-	cp -rav $workdir/syslinux/syslinux-*/bios/com32/lib/libcom32.c32             $workdir/binary/isolinux/	
-	cp -rav $workdir/syslinux/syslinux-*/bios/com32/libutil/libutil.c32          $workdir/binary/isolinux/
-	cp -rav $workdir/syslinux/syslinux-*/bios/com32/menu/vesamenu.c32            $workdir/binary/isolinux/
+	notice "Building syslinux"	
+	# source $R/extra/syslinux_builddeps
+	
+	cat <<EOF | sudo tee $workdir/env/build_syslinux
+#!/bin/bash
+var=\`sed '/^#/d' /home/syslinux/${sources}/debian/control\`
+var=\`echo \$var | awk -F"Build-Depends:" '{print \$2}'\`
+echo \$var > temp
+sed -i "s/[A-Z]/@/g" temp
+x=\`cat temp\`
+tmp=\${x%%@*}
+x=\${tmp%%,*}
+echo \${x%%" "*} > deps
+tmp=\${tmp#*,}
+while [[ \$tmp != " " ]]; do
+	x=\${tmp%%,*}
+	x=\${x#*" "}
+	echo \${x%%" "*}  >> deps
+	tmp=\${tmp#*,}
+done
+allpkgs="\$(apt-cache search '.' | cut -d' ' -f1)"
+list=()
+for i in \$(cat deps) ; do
+	for j in \`printf "%s" "\$allpkgs" | grep "^\$i$"\`; do
+		list+=" \$j"
+	done
+done
+echo \$list
+cd /home/syslinux/${sources}
+apt-get update
+apt-get --yes --force-yes install \$list
+make bios
+EOF
+
+	chroot-script -d build_syslinux $workdir/env || zerr
+	
+	mkdir -p $workdir/binary/isolinux	
+	
+	cp -rav $workdir/env/home/syslinux/$sources/bios/core/isolinux.bin                  $workdir/binary/isolinux/
+	cp -rav $workdir/env/home/syslinux/$sources/bios/com32/chain/chain.c32              $workdir/binary/isolinux/
+	cp -rav $workdir/env/home/syslinux/$sources/bios/com32/elflink/ldlinux/ldlinux.c32  $workdir/binary/isolinux/
+	cp -rav $workdir/env/home/syslinux/$sources/bios/com32/lib/libcom32.c32             $workdir/binary/isolinux/	
+	cp -rav $workdir/env/home/syslinux/$sources/bios/com32/libutil/libutil.c32          $workdir/binary/isolinux/
+	cp -rav $workdir/env/home/syslinux/$sources/bios/com32/menu/vesamenu.c32            $workdir/binary/isolinux/
 }
 
 iso_write_isolinux_cfg() {
 	fn iso_write_isolinux_cfg "(override)"
-	req=(workdir)
+	req=(R workdir os)
 	ckreq || return 1
 	
-	## overridden in blends
-	
-	#distrib=`echo "${blend_distribution}" | sed 's/^./\u&/'`		
-	#sed -i "s/${distrib} Live/${blend_distribution} ${version%%.*} ${label} ${kernel_flavor}/g" $workdir/binary/isolinux/menu.cfg
+	notice "copying isolinux overlay"
+	cp -rav $R/extra/isolinux-overlay/*.cfg $workdir/binary/isolinux/
+	cp -rav $R/extra/isolinux-overlay/splash.png $workdir/binary/isolinux/
 }
 
 iso_squash_strap() {
@@ -136,11 +146,12 @@ iso_squash_strap() {
 	esac
 	pushd $workdir
 	[[ -f binary/live/filesystem.squashfs ]] && rm -f binary/live/filesystem.squashfs
-	sudo mksquashfs $strapdir binary/live/filesystem.squashfs \
-		-no-recovery -always-use-fragments -b 1048576 -comp xz ${=_compfilt} -Xdict-size 75% || zerr
-
+	rm -f $strapdir/root/.bash_history
 	#~ sudo mksquashfs $strapdir binary/live/filesystem.squashfs \
-		#~ -comp xz ${=_compfilt} -noappend || zerr
+		#~ -no-recovery -always-use-fragments -b 1048576 -comp xz ${=_compfilt} -Xdict-size 75% || zerr
+
+	sudo mksquashfs $strapdir binary/live/filesystem.squashfs \
+		-comp xz ${=_compfilt} -noappend || zerr
 		
 
 	popd
@@ -148,7 +159,7 @@ iso_squash_strap() {
 
 iso_xorriso_build() {
 	fn iso_xorriso_build
-	req=(workdir image_name release_name)
+	req=(workdir arch earch blendlib version release make_isohybrid image_name release_name)
 	ckreq || return 1
 
 	notice "building iso..."
@@ -167,41 +178,63 @@ iso_xorriso_build() {
 	image_name="${blend_distribution}-${version}-${release_name}_${date_stamp}-${label}_${earch}"
 	echo "image_name: "${image_name}
 
-	[[ -n "$mkefi" ]] && {
-	uefi_opt="-eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot"
-	}
+	#~ [[ -n "$mkefi" ]] && {
+	#~ uefi_opt="-eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot"
+	#~ }
 
 	## this is a hack
-	isohybrid=/usr/lib/ISOLINUX/isohdpfx.bin #"$R"/extra/syslinux/isohdpfx.bin
+	# isohybrid=/usr/lib/ISOLINUX/isohdpfx.bin #"$R"/extra/syslinux/isohdpfx.bin
+	isohybrid="$R"/extra/syslinux/isohdpfx.bin
 
 	mkdir -p $R/dist
 	pushd $workdir
 	
-	sudo xorriso -as mkisofs -r -J -joliet-long -l \
+	[[ -f $workdir/binary/md5sums ]] && rm -f $workdir/binary/md5sums
+	
+	chmod -R 777 $workdir/binary
+	pushd $workdir/binary	
+	find . -xdev -type f -print0 | xargs -0 md5sum > md5sums
+	popd
+	
+	# If isohdpfx.bin gets moved again, maybe use:   isohdpfx=$(find /usr/lib/ -name isohdpfx.bin)
+    [[ $make_isohybrid = yes ]] && {
+       if [[ -f /usr/lib/syslinux/mbr/isohdpfx.bin ]] ; then
+          isohybrid=/usr/lib/syslinux/mbr/isohdpfx.bin
+       elif [[ -f /usr/lib/syslinux/isohdpfx.bin ]] ; then
+          isohybrid=/usr/lib/syslinux/isohdpfx.bin
+       elif [[ -f /usr/lib/ISOLINUX/isohdpfx.bin ]] ; then
+          #isohybrid_opt="-isohybrid-mbr "
+          isohybrid=/usr/lib/ISOLINUX/isohdpfx.bin
+		else
+		  echo "Can't create isohybrid.  File: isohdpfx.bin not found. The resulting image will be a standard iso file."
+		fi
+	}
+
+	xorriso -as mkisofs -r -J -joliet-long -l \
 		-isohybrid-mbr $isohybrid \
+		-o $R/dist/customiso.iso "$workdir/binary" \
 		-partition_offset 16 \
-		-A "${os} Live - ${arch}" \
+		-V "${blend_distribution} Live - ${flavor}" \
 		-b isolinux/isolinux.bin \
 		-c isolinux/boot.cat \
 		-no-emul-boot \
 		-boot-load-size 4 \
 		-boot-info-table \
-		${=uefi_opt} \
-		-o customiso.iso \
-		binary || zerr
+		-eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot
 
-		mv ./customiso.iso $R/dist/$image_name.iso 
+	mv $R/dist/customiso.iso $R/dist/$image_name.iso
 	
+	pushd $R/dist
+	md5sum $image_name.iso > $image_name.iso.md5
 	popd
-	unset uefi_opt
 
 	[[ "$DEBUG" = 1 ]] || {
-		[[ -n "$workdir" ]] && sudo rm -rf "$workdir"
+		[[ -n "$workdir" ]] && rm -rf "$workdir"
 	}
 }
 
 iso_genisoimage_build() {
-	fn iso_xorriso_build
+	fn iso_genisoimage_build
 	req=(workdir earch blendlib version release release_name)
 	ckreq || return 1
 
@@ -219,8 +252,6 @@ iso_genisoimage_build() {
 	release_label=$release
 	# image_name="${blend_distribution}-${version}-${release_label}_${date_stamp}-${label}_${earch}"
 	image_name="${blend_distribution}-${version}-${release_name}_${date_stamp}-${label}_${earch}"
-	
-	isohybrid="$R"/extra/syslinux/isohdpfx.bin
 
 	mkdir -p $R/dist
 	pushd $workdir
@@ -247,7 +278,9 @@ iso_genisoimage_build() {
 
 	mv $R/dist/customiso.iso $R/dist/$image_name.iso 
 	isohybrid $R/dist/$image_name.iso
-	md5sum $R/dist/$image_name.iso > $R/dist/$image_name.iso.md5
+	pushd $R/dist
+	md5sum $image_name.iso > $image_name.iso.md5
+	popd
 
 	[[ "$DEBUG" = 1 ]] || {
 		[[ -n "$workdir" ]] && rm -rf "$workdir"
@@ -392,5 +425,21 @@ EOF
 	
 	popd
 	unset tempdir efi_dir arch_efi boot_efi
-	
 }
+
+iso_set_variables() {
+	fn iso_set_variables
+	req=(workdir blend)
+	ckreq || return 1
+	
+	blend=${blendlib##*/}
+	blend_distribution=${blend%%-*}
+	label=`echo "${blend_distribution}" | sed 's/^./\u&/'`
+	
+	find $workdir/binary -name "*.cfg" -print | xargs sed -i "s/@MENU_TITLE@/${label} Live (${release}) - ${flavor}/g"
+	find $workdir/binary -name "*.cfg" -print | xargs sed -i "s/@DISTRO@/${label}/g"	
+	find $workdir/binary -name "*.cfg" -print | xargs sed -i "s/@COMPONENTS@/live components username=${blend_distribution} localhost=${blend_distribution} nocomponents=passwd splash quiet/g"
+	find $workdir/binary -name "*.cfg" -print | xargs sed -i "s/@ABINAME@/${abiname}/g"
+	find $workdir/binary -name "*.cfg" -print | xargs sed -i "s/@FLAVOR@/${flavor}/g"
+}
+
